spring:
  cloud:
    gateway:
      routes:
      - id: participant-service
        uri: lb://participant-service
        predicates:
        - Path=/participant/**
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

server:
  port: 9005